repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        files: ^api_v2/  # Only check files in the api_v2 folder
      - id: end-of-file-fixer
        files: ^api_v2/
      - id: check-yaml
        files: ^api_v2/
      - id: check-added-large-files
        files: ^api_v2/
      - id: check-merge-conflict
        files: ^api_v2/

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Replace with the latest version
    hooks:
      - id: black
        language_version: python3
        files: ^api_v2/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Replace with the latest version
    hooks:
      - id: flake8
        args: [--max-line-length=88]  # Match Black's default line length
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
        files: ^api_v2/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0  # Replace with the latest version
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^api_v2/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
        files: ^api_v2/
