services:
  mysql:
    build:
      context: db/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: msc_onlab
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass

  kong:
    image: kong:2.8.5
    volumes:
      - ./api_v2/kong/kong.yml:/usr/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8443:8443
    depends_on:
      - auth
      - keycloak

  auth:
    build:
      context: ./api_v2/auth
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 5000
      APP_DEBUG: True
      KEYCLOAK_SERVER_URL: http://keycloak:8080 # Kong OpenID Connect plugin is Enterprise plugin...
      KEYCLOAK_REALM_NAME: msc-onlab-test
      KEYCLOAK_CLIENT_ID: msc-onlab-auth-microservice-client-test
      KEYCLOAK_CLIENT_SECRET: moo8oexa0Aitoon8chohCaeh8eith5ei
      KEYCLOAK_ADMIN_USERNAME: realmadmin
      KEYCLOAK_ADMIN_PASSWORD: Asdasd11
      METRICS_PREFIX: msc_onlab
      METRICS_APP_NAME: auth
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "http://kong:8000/auth/health"]
      interval: 5s
      timeout: 60s
      retries: 5

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 5

  keycloak:
    image: docker.io/bitnami/keycloak:26.0.5
    ports:
      - 8080:8080
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pass
      KEYCLOAK_CREATE_ADMIN_USER: true
      # KEYCLOAK_DATABASE_VENDOR: postgres
      # KEYCLOAK_DATABASE_HOST: postgresql
      # KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: admin
      KEYCLOAK_DATABASE_PASSWORD: pass
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    volumes:
    - ./keycloak/realm.json:/opt/bitnami/keycloak/data/import/keycloak.default.realm.json
    depends_on:
      - postgresql
