---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: app-msc-dipterv-dev
data:
  kong.yml: |
    _format_version: "2.1"

    services:
      - name: auth_service
        url: http://auth.app-msc-dipterv-dev.svc.cluster.local:5000
        routes:
          - name: auth_route
            paths:
              - /auth

      - name: team_service
        url: http://team.app-msc-dipterv-dev.svc.cluster.local:5001
        routes:
          - name: team_route
            paths:
              - /team

      - name: task_service
        url: http://task.app-msc-dipterv-dev.svc.cluster.local:5002
        routes:
          - name: task_route
            paths:
              - /task

      - name: invitation_service
        url: http://invitation.app-msc-dipterv-dev.svc.cluster.local:5003
        routes:
          - name: invitation_route
            paths:
              - /invitation
