apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
spec:
  template:
    spec:
      containers:
      - name: db-migrator
        image: axelnemes/msc-dipterv-dev:db-migrator # {"$imagepolicy": "flux-system:msc-dipterv-dev-db-migrator"}
        envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-config
        env:
          - name: TIMEZONE
            value: "Europe/Budapest"
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        capabilities:
          drop:
            - all
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - worker
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rpw01
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rpw02
  backoffLimit: 4
