global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: backend-auth
    static_configs:
      - targets:
        - kong:8000
    metrics_path: /auth/metrics
