apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-msc-dipterv-dev-auth
  labels:
    application: app-msc-dipterv-dev-auth
spec:
  endpoints:
    - interval: 1m
      path: metrics
      port: http
  namespaceSelector:
    matchNames:
    - app-msc-dipterv-dev
  selector:
    matchLabels:
      application: auth
