apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-msc-dipterv-dev-task
  template:
    metadata:
      labels:
        app: app-msc-dipterv-dev-task
    spec:
      containers:
        - name: app-msc-dipterv-dev-task
          image: axelnemes/msc-dipterv-dev:task-202505181110-8589594 # {"$imagepolicy": "flux-system:msc-dipterv-dev-task"}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - name: http
              containerPort: 5002
              protocol: TCP
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-config
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-config
          env:
            - name: METRICS_PREFIX
              value: "msc_onlab_dev"
            - name: METRICS_APP_NAME
              value: "task"
            - name: TEAM_SERVICE_HOST
              value: "team.app-msc-dipterv-dev.svc.cluster.local"
            - name: TEAM_SERVICE_PORT
              value: "5001"
            - name: AUTH_SERVICE_HOST
              value: "auth.app-msc-dipterv-dev.svc.cluster.local"
            - name: AUTH_SERVICE_PORT
              value: "5000"
            - name: TIMEZONE
              value: "Europe/Budapest"
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 5002
            failureThreshold: 30
            periodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        capabilities:
          drop:
            - all
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - worker
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rpw01
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - rpw02
