apiVersion: v1
data:
  MYSQL_INVITATION_PASSWORD: cGFzcw==
  MYSQL_MIGRATOR_PASSWORD: cGFzcw==
  MYSQL_TASK_PASSWORD: cGFzcw==
  MYSQL_TEAM_PASSWORD: cGFzcw==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-config
