apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  configmap: |
    KEYCLOAK_SERVER_URL: http://keycloak.nemes.live
    KEYCLOAK_REALM_NAME: msc-onlab
    KEYCLOAK_CLIENT_ID: msc-onlab-auth-microservice-client
    KEYCLOAK_ADMIN_USERNAME: realmadmin
    METRICS_PREFIX: msc_onlab
    METRICS_APP_NAME: auth
    CONFIGMAP_TEST: hello_world
