apiVersion: v1
kind: Secret
metadata:
  name: keycloak-config
data:
  keycloak: S0VZQ0xPQUtfQ0xJRU5UX1NFQ1JFVDogbW9vOG9leGEwQWl0b29uOGNob2hDYWVoOGVpdGg1ZWkKS0VZQ0xPQUtfQURNSU5fUEFTU1dPUkQ6IEFzZGFzZDEx
