apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-msc-dipterv-dev
  labels:
    application: app-msc-dipterv-dev
spec:
  endpoints:
    - interval: 1m
      path: auth/metrics
      port: proxy
    - interval: 1m
      path: team/metrics
      port: proxy
  namespaceSelector:
    matchNames:
    - app-msc-dipterv-dev
  selector:
    matchLabels:
      name: kong
