name: "[DEV] Build and Push"
run-name: "[DEV] Build and Push: ${{ github.sha }}"

on:
  push:
    branches:
      - dev
    paths:
      - 'api/auth/**'
      - 'api/team/**'
      - 'api/task/**'
      - 'api/invitation/**'
      - 'api/db_migrator/**'

env:
  BUILD_ENVIRONMENT: dev

jobs:
  gather-informations:
    runs-on: ubuntu-latest
    outputs:
      build_time: ${{ steps.date.outputs.date }}
      build_environment: ${{ steps.environment.outputs.build_environment }}
    steps:
      - id: date
        name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - id: environment
        name: Get build environment
        run: echo "build_environment=$BUILD_ENVIRONMENT" >> "$GITHUB_OUTPUT"

  bap-db-migrator:
    needs:
      - gather-informations
    uses: ./.github/workflows/db-migrator.yaml
    with:
      environment: ${{ needs.gather-informations.outputs.build_environment }}
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  bap-auth:
    needs:
      - gather-informations
    uses: ./.github/workflows/auth-service.yaml
    with:
      environment: ${{ needs.gather-informations.outputs.build_environment }}
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  bap-team:
    needs:
      - gather-informations
    uses: ./.github/workflows/team-service.yaml
    with:
      environment: ${{ needs.gather-informations.outputs.build_environment }}
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  bap-task:
    needs:
      - gather-informations
    uses: ./.github/workflows/task-service.yaml
    with:
      environment: ${{ needs.gather-informations.outputs.build_environment }}
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  bap-invitation:
    needs:
      - gather-informations
    uses: ./.github/workflows/invitation-service.yaml
    with:
      environment: ${{ needs.gather-informations.outputs.build_environment }}
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
