name: "[DEV] Build and Push"
run-name: "[DEV] Build and Push: ${{ github.sha }}"

on:
  push:
    branches:
      - dev
    paths:
      - 'api/auth/**'
      - 'api/team/**'
      - 'api/task/**'

env:
  BUILD_ENVIRONMENT: dev

jobs:
  gather-informations:
    runs-on: ubuntu-latest
    outputs:
      build_time: ${{ steps.date.outputs.date }}
    steps:
      - id: date
        name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  auth-service:
    needs:
      - gather-informations
    uses: ./.github/workflows/auth-service.yaml
    with:
      environment: $BUILD_ENVIRONMENT
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  team-service:
    needs:
      - gather-informations
    uses: ./.github/workflows/team-service.yaml
    with:
      environment: $BUILD_ENVIRONMENT
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  task-service:
    needs:
      - gather-informations
    uses: ./.github/workflows/task-service.yaml
    with:
      environment: $BUILD_ENVIRONMENT
      date: ${{ needs.gather-informations.outputs.build_time }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
